const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
function store(saved='[]'){
 const elements=new Map(), events={}, storage=new Map([['dne-cart',saved]]);
 const element=()=>({innerHTML:'',textContent:'',value:1,disabled:true,classList:{add(){},remove(){},toggle(){}},setAttribute(){},scrollIntoView(){}});
 const context=vm.createContext({Intl,JSON,Number,Math,String,setTimeout:()=>1,clearTimeout(){},location:{hash:'#/'},window:{scrollTo(){},addEventListener(){}},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},document:{querySelector:s=>{if(!elements.has(s))elements.set(s,element());return elements.get(s);},querySelectorAll:()=>[],addEventListener:(name,fn)=>events[name]=fn}});
 vm.runInContext(fs.readFileSync('app.js','utf8'),context);
 return {context,elements,storage,run:s=>vm.runInContext(s,context),click:(dataset,id)=>events.click({target:{closest:()=>({dataset,id})}}),submit:()=>events.submit({target:{id:'checkout-form'},preventDefault(){}})};
}
test('homepage lists all nine supplied designs with direct product links',()=>{const s=store();const html=s.elements.get('#app').innerHTML;assert.equal((html.match(/class="product-card"/g)||[]).length,9);for(let i=1;i<=9;i++){assert.ok(html.includes(`assets/design-${i}.png`));assert.ok(fs.existsSync(`assets/design-${i}.png`));}assert.ok(html.includes('#/product/yellow-camo-set'));});
test('size selection, quantity, merging, persistence, and checkout',()=>{const s=store();s.run("location.hash='#/product/yellow-camo-set';render()");assert.ok(s.elements.get('#app').innerHTML.includes('disabled>SELECT A SIZE'));s.click({size:'M'});s.click({qty:'1'});s.click({product:'yellow-camo-set'},'add-to-bag');let bag=JSON.parse(s.storage.get('dne-cart'));assert.deepEqual(bag,[{id:'yellow-camo-set',size:'M',qty:2}]);s.click({product:'yellow-camo-set'},'add-to-bag');assert.equal(JSON.parse(s.storage.get('dne-cart'))[0].qty,4);s.click({size:'L'});s.click({product:'yellow-camo-set'},'add-to-bag');assert.equal(JSON.parse(s.storage.get('dne-cart')).length,2);const restored=store(s.storage.get('dne-cart'));assert.equal(restored.run('subtotal()'),1200);restored.run("location.hash='#/checkout';render()");assert.ok(restored.elements.get('#app').innerHTML.includes('PAY WITH STRIPE'));assert.ok(restored.elements.get('#app').innerHTML.includes('$10.00'));});
test('cart edits and removal update totals, corrupted storage recovers',()=>{const s=store('[{"id":"linear-set","size":"S","qty":2}]');s.run("location.hash='#/cart';render()");s.click({cartIndex:'0',cartDelta:'-1'});assert.equal(s.run('subtotal()'),200);s.click({remove:'0'});assert.equal(s.run('subtotal()'),0);assert.ok(s.elements.get('#app').innerHTML.includes('YOUR BAG IS WIDE OPEN'));assert.equal(store('invalid').run('cart.length'),0);assert.equal(store('[{"id":"missing","size":"S","qty":2}]').run('cart.length'),0);});
test('filters and detail zoom use the supplied images',()=>{const s=store();s.click({filter:'Short sets'});assert.equal((s.elements.get('#products').innerHTML.match(/class="product-card"/g)||[]).length,2);s.run("location.hash='#/product/stargazer-set';render()");s.click({view:'detail'});assert.ok(s.elements.get('#main-product').innerHTML.includes('assets/design-3.png'));assert.ok(s.elements.get('#main-product').innerHTML.includes('detail-zoom'));});
